<<<<<<< HEAD
extends: 'airbnb-base'
plugins:
  - import
rules:
  no-console: 'off'
  import/extensions: 'off'
=======
extends: 'airbnb-base'
plugins:
  - import
rules:
  no-console: 'off'
  import/extensions: 'off'
>>>>>>> 7d66de9 (Co-authored-by: Daniil Shtarkman <95107643+Masterofowls@users.noreply.github.com>)
